const state={members:[],vehicles:[]};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('');
const fmt=d=>d?new Date(d).toLocaleString():'—';
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.style.background=error?'#9b2525':'#13283c';el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)}
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data}
async function load(){try{Object.assign(state,await api('/api/state'));const expected=document.body.dataset.page;if(state.role!==expected){location.href=`/login?next=${expected}`;return}if(expected==='manager')renderManager();else if(expected==='admin')renderAdmin();else renderTeam()}catch(e){if(e.message.includes('sign in'))location.href='/login';else throw e}}
function pill(value){return `<span class="pill ${String(value).toLowerCase()}">${esc(value)}</span>`}
function programPill(value){const key=String(value).toLowerCase().replaceAll(' ','-');return `<span class="pill program ${key}">${esc(value)}</span>`}
function availableMembers(exclude){return state.members.filter(m=>m.available_today&&m.current_load===0&&m.id!==exclude)}
function renderManager(){
 const q=state.vehicles.filter(v=>v.status==='Queued').length,a=state.vehicles.filter(v=>v.status==='Assigned').length,c=state.vehicles.filter(v=>v.status==='Completed').length,av=availableMembers().length;
 $('#stats').innerHTML=[[q,'Vehicles queued'],[a,'In progress'],[av,'Teammates available'],[c,'Completed']].map(x=>`<div class="stat"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');
 const select=$('#memberId');select.innerHTML='<option value="">Select teammate</option>'+availableMembers().map(m=>`<option value="${m.id}">${esc(m.name)} · load ${m.overall_load}</option>`).join('');
 const body=$('#vehicleRows');body.innerHTML=state.vehicles.length?state.vehicles.map(v=>`<tr><td class="vin">${esc(v.vin)}</td><td>${programPill(v.program)}</td><td>${esc(v.location)}</td><td>${pill(v.status)}</td><td>${esc(v.assigned_name||'—')}</td><td>${v.assignment_type?pill(v.assignment_type):'—'}</td><td>${fmt(v.assigned_at)}</td><td>${fmt(v.completed_at)}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">No vehicles yet</td></tr>';
 $('#teamsState').textContent=state.teamsConfigured?'Teams notifications connected':'Teams webhook not configured';$('#teamsState').className='notice '+(state.teamsConfigured?'':'warn');
}
function renderTeam(){
 $('#memberCards').innerHTML=state.members.map(m=>{const status=m.current_load?'Vehicle in progress':m.available_today?`Available · ${m.overall_load} total (${m.auto_count} auto / ${m.manual_count} manual)`:`Unavailable · ${m.overall_load} total (${m.auto_count} auto / ${m.manual_count} manual)`;return `<div class="member ${!m.available_today?'unavailable':''}"><div class="member-info"><div class="avatar">${initials(m.name)}</div><div><strong>${esc(m.name)}</strong><small>${status}</small></div></div><label class="switch" title="Available today"><input type="checkbox" ${m.available_today?'checked':''} ${m.current_load?'disabled':''} onchange="availability(${m.id},this.checked)"><span class="slider"></span></label></div>`}).join('');
 const active=state.vehicles.filter(v=>v.status==='Assigned');$('#activeRows').innerHTML=active.length?active.map(v=>`<tr><td><strong>${esc(v.assigned_name)}</strong></td><td class="vin">${esc(v.vin)}</td><td>${programPill(v.program)}</td><td>${esc(v.location)}</td><td>${esc(v.comments||'—')}</td><td>${pill(v.assignment_type)}</td><td>${fmt(v.assigned_at)}</td><td><div class="actions"><button class="secondary small" onclick="openReassign(${v.id})">Reassign</button><button class="danger small" onclick="completeVehicle(${v.id})">Complete</button></div></td></tr>`).join(''):'<tr><td colspan="8" class="empty">No vehicles in progress</td></tr>';
}
function renderAdmin(){
 const total=state.members.reduce((sum,m)=>sum+m.overall_load,0),manual=state.members.reduce((sum,m)=>sum+m.manual_count,0),auto=state.members.reduce((sum,m)=>sum+m.auto_count,0),active=state.members.reduce((sum,m)=>sum+m.current_load,0);
 $('#stats').innerHTML=[[total,'Overall assignments'],[auto,'Automatic'],[manual,'Manual'],[active,'Currently active']].map(x=>`<div class="stat"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');
 $('#adminRows').innerHTML=state.members.map(m=>`<tr><td><strong>${esc(m.name)}</strong></td><td>${m.current_load}</td><td>${m.overall_load}</td><td>${m.auto_count}</td><td>${m.manual_count}</td><td><button class="secondary small" onclick="openCountCorrection(${m.id})">Edit counts</button></td></tr>`).join('');
 const month=$('#reportMonth');if(!month.value)month.value=new Date().toISOString().slice(0,7);$('#downloadCsv').href=`/api/admin/export?month=${encodeURIComponent(month.value)}`;month.onchange=()=>$('#downloadCsv').href=`/api/admin/export?month=${encodeURIComponent(month.value)}`;
}
document.addEventListener('DOMContentLoaded',()=>{load().catch(e=>toast(e.message,true));setInterval(()=>load().catch(()=>{}),15000);const form=$('#vehicleForm');if(form){form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form),mode=fd.get('assignMode');const body=Object.fromEntries(fd);if(mode==='Manual'&&!body.memberId)return toast('Select a teammate for manual assignment.',true);try{const result=await api('/api/vehicles',{method:'POST',body:JSON.stringify(body)});toast(result.assignedTo?`Assigned to ${result.assignedTo}${result.teamsSent?' · Teams notified':''}`:'Vehicle added to queue');form.reset();await load()}catch(err){toast(err.message,true);await load()}});document.querySelectorAll('input[name=assignMode]').forEach(x=>x.addEventListener('change',()=>$('#manualField').hidden=x.value!=='Manual'||!x.checked));}});
async function assign(id){try{const r=await api(`/api/vehicles/${id}/assign`,{method:'POST',body:JSON.stringify({assignMode:'Auto'})});toast(`Assigned to ${r.assignedTo}${r.teamsSent?' · Teams notified':''}`);await load()}catch(e){toast(e.message,true)}}
async function completeVehicle(id){if(!confirm('Mark this vehicle completed?'))return;try{const r=await api(`/api/vehicles/${id}/complete`,{method:'POST',body:'{}'});toast(r.autoAssigned?`Completed · queued VIN ${r.autoAssigned} assigned to ${r.assignedTo}`:'Vehicle completed');await load()}catch(e){toast(e.message,true)}}
function openReassign(id){const v=state.vehicles.find(x=>x.id===id),d=$('#reassignDialog');$('#reassignVehicleId').value=id;$('#reassignMember').innerHTML=availableMembers(v.assigned_to).map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('');d.showModal()}
async function submitReassign(){try{const id=$('#reassignVehicleId').value;await api(`/api/vehicles/${id}/reassign`,{method:'POST',body:JSON.stringify({memberId:$('#reassignMember').value,reason:$('#reassignReason').value})});$('#reassignDialog').close();toast('Vehicle reassigned');await load()}catch(e){toast(e.message,true)}}
async function availability(id,available){try{const r=await api(`/api/members/${id}/availability`,{method:'POST',body:JSON.stringify({available})});if(r.autoAssigned)toast(`Queued VIN ${r.autoAssigned} automatically assigned to ${r.assignedTo}`);await load()}catch(e){toast(e.message,true);await load()}}
async function logout(){await api('/api/logout',{method:'POST',body:'{}'});location.href='/login'}
async function resetCounts(){const month=$('#reportMonth').value;if(!month)return toast('Select a reporting month.',true);if(!confirm(`Close ${month} and reset monthly Overall, Auto, and Manual counts? Current Load will not change.`))return;try{const r=await api('/api/admin/reset-counts',{method:'POST',body:JSON.stringify({month})});toast(`${r.period} archived · ${r.membersArchived} teammate counters reset`);await load()}catch(e){toast(e.message,true)}}
function openCountCorrection(id){const member=state.members.find(m=>m.id===id);$('#countMemberId').value=id;$('#countMemberName').textContent=`${member.name} · Current Load ${member.current_load}`;$('#autoCount').value=member.auto_count;$('#manualCount').value=member.manual_count;$('#countDialog').showModal()}
async function saveCounts(){const id=$('#countMemberId').value,autoCount=Number($('#autoCount').value),manualCount=Number($('#manualCount').value);if(!Number.isInteger(autoCount)||!Number.isInteger(manualCount)||autoCount<0||manualCount<0)return toast('Enter whole numbers of zero or greater.',true);try{const r=await api(`/api/admin/members/${id}/counts`,{method:'POST',body:JSON.stringify({autoCount,manualCount})});$('#countDialog').close();toast(`Counts corrected · Overall ${r.overallLoad}`);await load()}catch(e){toast(e.message,true)}}
async function recalculateLoads(){if(!confirm('Recalculate every Current Load from active vehicle assignments?'))return;try{await api('/api/admin/recalculate-loads',{method:'POST',body:'{}'});toast('Current loads recalculated from active vehicles');await load()}catch(e){toast(e.message,true)}}
